# Generated by Django 4.1.3 on 2022-12-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=20)),
                ('iconclass', models.CharField(max_length=30)),
                ('duration', models.DurationField()),
                ('eventdate', models.DateField()),
                ('discription', models.TextField()),
            ],
            options={
                'db_table': 'EventInfo',
            },
        ),
    ]
