# Generated by Django 4.1.7 on 2023-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=12)),
                ('alt_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
